package edu.mfldclin.mcrf.vakilabad.gui;

import edu.mfldclin.mcrf.vakilabad.log.LogRecord;
import edu.mfldclin.mcrf.vakilabad.log.LogService;
import javax.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author Ehsun Behravesh <post@ehsunbehravesh.com>
 */
@Component
@Scope(value = "prototype")
public class LogFrame extends javax.swing.JFrame {

    private static final Logger log = LoggerFactory.getLogger(LogFrame.class);

    @Autowired
    private LogService logService;

    /**
     * Creates new form LogFrame
     */
    public LogFrame() {
        initComponents();
    }

    @PostConstruct
    public void init() {
        log.info("Adding LogFrame instance to the LogMonitors of LogService: " + this);
        logService.addMonitor((LogRecord logRecord) -> {
            logReceived(logRecord);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaMain = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txaMain.setColumns(20);
        txaMain.setRows(5);
        jScrollPane1.setViewportView(txaMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaMain;
    // End of variables declaration//GEN-END:variables

    private void logReceived(LogRecord logRecord) {
        log.debug("LogFrame log received: " + logRecord);
        txaMain.append(logRecord.getValue().concat("\n"));
    }
}
